#!/usr/bin/python3
import os
import py_compile

pyfile = os.environ.get('PYFILE')
if pyfile:
    pyfilec = pyfile + 'c'
    py_compile.compile(pyfile, cfile=pyfilec)
    print(f"Compilation successful: {pyfilec}")
else:
    print("Error: PYFILE environment variable not set.")
